scylladb/scylla-operator-images

- Makefile
- node-setup/Dockerfile
This PR introduces a Dockerfile and necessary Makefile changes for creating `node-setup` image. The image installs `xfsprogs` package on top of `base-ubuntu` image.
The image is required for the setup of local volumes in `scylla-operator`'s CI (https://github.com/scylladb/scylla-operator/pull/979).
> Add node-setup image

- golang/1.18/Dockerfile
Updates golang-1.18 to 1.18.5 and cleans up after apt.
> Update Golang to 1.18.5

- golang/1.18/Dockerfile
- golang/1.18/download-file.sh
- golang/1.19/Dockerfile
- golang/1.19/download-file.sh
This adds:
- Golang 1.19.1 - (it's time)
- Checksum verification (security)
- Bumps golang 1.18 from 1.18.5 to 1.18.6 (security)
> Add Golang 1.19 and verify checksums

- Makefile
Followup to https://github.com/scylladb/scylla-operator-images/pull/3 to build and publish the Golang 1.19 image.
> Build and publish Golang 1.19

- golang/1.18/Dockerfile
- golang/1.19/Dockerfile
https://github.com/scylladb/scylla-operator-images/pull/3 has accidentally removed the `/tmp` folder instead of cleaning it. We want only to remove any files inside it.
> Fix /tmp folder in Golang images

- .github/workflows/go.yaml
Stops tagging people for internal Slack messages. It's now posted to a dedicated channel so anyone can manage their preferences there.
> Remove CC from Slack failure report

- golang/1.18/Dockerfile
- golang/1.19/Dockerfile
- golang/1.20/Dockerfile
When executing build scripts, it's helpful to have yq around. Having extra tools in golang image is fine as this is not a production runtime.
> Add yq to golang images for build tooling

- Makefile
- kube-tools/latest/Dockerfile
This PR add a rolling image that contains various tools we need for container based CI. Say, to deploy an app, you need `kubectl apply` and `yq`. We can later extend it with others that are needed.
This is a special case of a rolling image where we are in control and versioning a set of tools would have more downsides then the stability benefit.
> Add kube-tools for CI jobs

- Makefile
- kube-tools/latest/Dockerfile
To be able to run e2e suite from an image locally, we need podman available. It's easier to base this image on the most complex component (requires config to run inside containers), and add the easier ones.
This is using fedora:38 as a base.
> Add podman to kube-tools

- golang/1.18/Dockerfile
- golang/1.19/Dockerfile
- golang/1.20/Dockerfile
- kube-tools/latest/Dockerfile
This fixes `yq` command that was only installed into GOPATH but that wasn't included in PATH.
> Fix yq instalation

- golang/1.20/Dockerfile
Our verify jobs need helm to generate manifests.
> Add helm to golang builders

- kube-tools/latest/Dockerfile
Skopeo allows us to check manifests without pulling images and with a bit of bash it can wait for images to be available.
> Add skopeo to kube-tools

- kube-tools/latest/Dockerfile
Podman 4.5 is currently unavailable due to:
https://github.com/containers/podman/discussions/19796
> Bump podman base in kube-tools image to 4.6

- golang/1.20/Dockerfile
`gcc`, `g++`, `libc6-dev` are required by cgo which is required for running race detector in tests.
`dbus-x11` is required by our tests to run `dbus-launch`.
> Install packages required by unit tests in golang image

- golang/1.18/download-file.sh
- golang/1.19/download-file.sh
- golang/1.20/download-file.sh
To retry SSL connection errors (and others) `curl` needs `--retry-all-errors` flag.
> Retry all errors when downloading Golang archives

- golang/1.20/download-file.sh
When retrying a download far enough output redirection will still have the old data and fail the checksum. Using `-o` instead avoids it.
> Make sure there is no old data on curl retries

- poetry/1.5/Dockerfile
Sphinx multiversion checks out different branches and needs git.
> Add git to poetry for sphinx multiversion builds

- golang/1.20/Dockerfile
- golang/1.21/Dockerfile
This PRs add govulncheck to your golang image so we can use it for security scanning.
https://go.dev/blog/vuln
/cc @rzetelskik
> Add govulncheck to golang images

- buildah/latest/Dockerfile
On prow the git is created by a sidecar, so the owners are by nature not matching.
`fatal: detected dubious ownership in repository at '/home/prow/go/src/github.com/scylladb/scylla-operator'`
Fixes https://github.com/scylladb/scylla-operator-release/issues/136
> Disable git owners checks in buildah image for prow

- buildah/latest/Dockerfile
Using system config puts it into `/etc/gitconfig` that works everywhere, contrary to `/root/.gitconfig` which won't work unless that's your home dir.
Fixes https://github.com/scylladb/scylla-operator-release/issues/136
> Use system config for buildah git config

- golang/1.21/Dockerfile
- golang/1.22/Dockerfile
Bumps Go 1.21 image to 1.21.11, and 1.22 to 1.22.4.
/cc @tnozicka
> Bump Go images to latest stable versions

- kube-tools/latest/Dockerfile
`yq` is already available, `jq` is useful as well. 
Fixes:
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator-enterprise/44/pull-scylla-operator-enterprise-master-e2e-gke-release-script-latest/1825931338994159616
> Add jq to kube-tools image

- poetry/1.8/Dockerfile
This PR updates python version used in poetry-1.8 image to 3.12.
Required by https://github.com/scylladb/scylla-operator/pull/2132.
```
The currently activated Python version 3.9.18 is not supported by the project (^3.10).
Trying to find and use a compatible version. 
```
/kind feature
/priority important-soon
/cc zimnx
> Update python version to 3.12 in poetry 1.8 image

- poetry/1.8/Dockerfile
`distutils` package was removed from python 3.12 https://peps.python.org/pep-0632/, which causes jobs building docs in scylla-operator master to fail after poetry image update to 1.8. This PR downgrades python version used in poetry-1.8 image to 3.11.
/kind bug
/priority critical-urgent
/cc zimnx
> Downgrade python version to 3.11 in poetry 1.8 image

- base/ubi/9.4-minimal/Dockerfile
`kubectl cp` requires `tar` binary in the target image so we need to include it in the UBI base image used as a runtime.
Resolves #66
> Add tar to UBI base image so it works with kubectl cp

- base/ubi/9.4-minimal/Dockerfile
This PR adds `find` command into the ubi-9.4 base images that is needed by scylla operator node tuning.
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2121/pull-scylla-operator-master-e2e-gke-parallel/1841429706876915712/artifacts/must-gather/0/namespaces/scylla-operator-node-tuning/pods/cluster-node-setup-5wg9x/scylla-node-config.previous
```
2024-10-02T11:01:32.380604359Z ++ mktemp -d
2024-10-02T11:01:32.381935808Z + cd /tmp/tmp.7CEiQTLv9l
2024-10-02T11:01:32.382202238Z ++ find /host -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
2024-10-02T11:01:32.382265938Z /usr/bin/bash: line 8: find: command not found
2024-10-02T11:01:32.382660458Z ++ find /host -mindepth 1 -maxdepth 1 -type f -printf '%f\n'
2024-10-02T11:01:32.382680518Z …
```
> Add findutils needed by node tuning

- base/ubi/9.4-minimal/Dockerfile
This PR adds `mount` command into our base image that's used by scylla-operator node tuning.
```
2024-10-03T15:02:56.482957195Z ++ mktemp -d
2024-10-03T15:02:56.484417583Z + cd /tmp/tmp.x1iSU76bK0
2024-10-03T15:02:56.484703683Z ++ find /host -mindepth 1 -maxdepth 1 -type d -printf '%f\n'
2024-10-03T15:02:56.485646042Z + for d in $( find /host -mindepth 1 -maxdepth 1 -type d -printf '%f\n' )
2024-10-03T15:02:56.485650702Z + mkdir -p ./home
2024-10-03T15:02:56.486823440Z + mount --rbind /host/home ./home
2024-10-03T15:02:56.487044450Z /usr/bin/bash: line 10: mount: command not found
```
https://gcsweb.scylla-operator.scylladb.com/gcs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2121/pull-scylla-operator-master-e2e-gke-parallel/1841852773419716608/artifacts/must-gather/0/namespa …
> Add mount command needed by scylla-operator node tuning

- node-setup/Dockerfile
Image is used only in Operator E2E tests.
Required by https://github.com/scylladb/scylla-operator/pull/2175
> Add netcat to node-setup helper image

- golang/1.23/Dockerfile
- golang/1.24/Dockerfile
`diff` command used by our Makefile was removed in recent UBI's. This installs it explicitly.
```
$ podman run -ti --pull=always --entrypoint=/bin/bash --rm quay.io/scylladb/scylla-operator-images:golang-1.24
[root@c59ef1b1755a /]# diff
bash: diff: command not found
$ podman run -ti --pull=always --entrypoint=/bin/bash --rm quay.io/scylladb/scylla-operator-images:golang-1.23                                                            
[root@ecf73436f209 /]# diff
bash: diff: command not found
```
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2524/pull-scylla-operator-master-verify-deps/1904523847495847936
> Add diffutils package to golang images

- golang/1.24/Dockerfile
Turns out we don't have `file` in `golang-1.24` image:
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2885/pull-scylla-operator-master-verify/1956013190445797376#1:build-log.txt%3A313
/cc czeslavo
> Add file to golang-1.24 image

- OWNERS
- OWNERS_ALIASES
Part of https://github.com/scylladb/scylla-operator-team/issues/20.
Also ports https://github.com/scylladb/scylla-operator/pull/2936 to this repo.
/cc rzetelskik
/priority important-soon
> Make OWNERS and OWNERS_ALIASES consistent with scylla-operator
